### ISSUE TITLE
Descompuse el video :(

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#15]
Y se ve negro mientras no se carga..

Edite el video para que fuera mas rapido y asi... pero no charca...

Ayuuudaaaaa

> > > http://grab.by/HRI8

**Comment by enrique-ramirez** [comment]
Jajajaja ¿Qué le hiciste? :(

**Comment by enrique-ramirez** [comment]
https://mega.nz/#!hpMGEYBJ!Nqw9pXc2xgsbxo67otUIVmtfm6ePyEVVyGoFhXLYAqo

Este es el video original. No sé cómo comprimirlo más. :(

**Comment by enrique-ramirez** [comment]
Volví a subir el video original (24mb). Ya sirve, pero no sé cómo comprimirlo más sin que valga cabeza todo. :(

**Comment by solojavier** [comment]
:( ... ya habia editado el video pero bueno pues luego veo

**Comment by solojavier** [comment]
Creo que ya pude :)
