### ISSUE TITLE
En el home falta el boton de inspirate hasta abajo

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#18]
![home](https://cloud.githubusercontent.com/assets/1088010/8021717/ab361da2-0c70-11e5-93a1-ed361f604988.jpg)

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/jovenes.inspira.ac/commit/12a45111fec4bc905af82dd489fdd6180e11b251
