### ISSUE TITLE
En los valores de Nosotros... falta un pequeño filtro morado

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#20]
Que hace que se lean mejor las letras....

**Comment by solojavier** [comment]
http://grab.by/HRIm

**Comment by enrique-ramirez** [comment]
Estoy confundido. ¿Qué filtro morado?

**Comment by solojavier** [comment]
Las imagenes... no tienen su color natural... tienen como una mascara o filtro o cosa de color encima que hacen que las letras blancas se vean mejor....

**Comment by solojavier** [comment]
si?

**Comment by enrique-ramirez** [comment]
Try this: https://css-tricks.com/tinted-images-multiple-backgrounds/

**Comment by enrique-ramirez** [comment]
![screen shot 2015-06-16 at 8 56 19 am](https://cloud.githubusercontent.com/assets/1190640/8184729/97e29572-1405-11e5-8945-15001d2d33f8.png)

Lo siento. Con CSS solamente no se puede (culpa a los hexágonos. :( ). Van a tener que ser las imágenes editadas. :(

**Comment by solojavier** [comment]
OK :(
