### ISSUE TITLE
muy grandes las letras de cada quien se inspira de forma diferente en iOS

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#23]
![img_2485](https://cloud.githubusercontent.com/assets/1088010/8021744/33fa487e-0c72-11e5-98e6-b4e727af4f36.PNG)

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/jovenes.inspira.ac/commit/33f3e95c38457f522ead5e9023c85ab229065954
