### ISSUE TITLE
Se ver cortado banner y boton de busqueda sale abajo chueco...

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#24]
![img_2486](https://cloud.githubusercontent.com/assets/1088010/8021752/93673902-0c72-11e5-9c3f-bef9f37a36ab.PNG)

**Comment by solojavier** [comment]
Tambien en el blog sale igual....

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/jovenes.inspira.ac/commit/7cd05d598ce9286b80faedee38319d1e21137613
&&
https://github.com/softcraft/jovenes.inspira.ac/commit/0115554d1ebbe425bc8b670437a85394b81cdf66
