### ISSUE TITLE
Se puede que el video del home se vea más de lo ancho?

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#25]
Ya subí la nueva versión del video, pero a como se corta, no se alcanza a ver la frase completa... supongo que por la resolución que es diferente a la que había o algo...

Se puede ajustar para que se vea al menos la frase completa de la pared?

:)

**Comment by enrique-ramirez** [comment]
- [x] Reducir el alto del video a 450px (ajustes necesarios).

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/jovenes.inspira.ac/commit/2a53239d61b3a2a0cd3373ee64ef7cbf1d01c250
