### ISSUE TITLE
Fotos de proyectos no salen bien :/

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#3]
Aqui la prueba: http://grab.by/Hu14

**Comment by solojavier** [comment]
Al parecer es cuando las imagenes no son cuadradas o algo.

**Comment by enrique-ramirez** [comment]
Fixed: 
https://github.com/softcraft/jovenes.inspira.ac/commit/618a109dfc8cfbfe5d5068c9426fa998938efe9a
