### ISSUE TITLE
FIltro de ciudad en blog no sirve

### ISSUE THREAD

**Issue by solojavier** [softcraft/jovenes.inspira.ac#9]
http://grab.by/Hu28

**Comment by enrique-ramirez** [comment]
Debería estar arreglado aquí:
https://github.com/softcraft/jovenes.inspira.ac/commit/88398f88ac8c25271ed08df2313887d027c26835

**Comment by solojavier** [comment]
Ya estan los cambios en el servidor?? Porque aqui sigo sin verlo funcionar :(

**Comment by solojavier** [comment]
@enrique-ramirez  ^

**Comment by enrique-ramirez** [comment]
Fixed: https://github.com/softcraft/jovenes.inspira.ac/commit/a41ceeef8f93b536cd3f5466a69c586014c24938
